package com.kpcard.jpa.type;

public enum RedemptionTextType {
	REDEMPTION_INFORMATION,
	IN_STORE_INSTRUCTIONS,
	ON_LINE_INSTRUCTIONS,
	REDEMPTION_LINE_1,
	REDEMPTION_LINE_2,
	SALES_ASSOCIATE_INSTRUCTIONS
}
