package com.kpcard.jpa.type;

/**
 * 지원기능 유형
 * @author happymoney
 *
 */
public enum SupportedFeatures {
	PHYSICAL_CARD,
	VIRTUAL_CARD,
	REPLACEABLE_CARD,
	TRANSFERABLE_CARD,
	BALANCE_MERGES,
	CARDS_EXPIRE,
	WALLET_ADD_QR_CODE,
	UNIVERSAL_BALANCE_INQUIRY,
	PARTIAL_BALANCE_INQUIRY,
	REDEMPTION,
	VOID_REDEMPTION,
	RELOAD,
	VOID_RELOAD,
	REGIFT,
	TRANSACTION_HISTORY,
	VOID_ACTIVATION,
	HAS_PHONE_SUPPORT_AT_POS
}
