package com.kpcard.jpa.account;

import java.math.BigDecimal;
import java.util.Currency;
import java.util.Date;

import com.kpcard.jpa.type.AccountTransactionStatus;
import com.kpcard.jpa.type.AccountTransactionType;
import com.kpcard.jpa.type.AccountType;
import com.kpcard.jpa.type.MessageReasonCode;
import com.kpcard.jpa.type.PaymentNetworkType;
import com.kpcard.jpa.type.PaymentProcessor;

public class AccountTransaction {
	private String	id;
	private String	notes;
	private Date	createdTimestamp;
	private Date	updatedTimestamp;
	private String	baseTransactionId;
	private String	correlationId;
	private String	accountId;
	private String	merchantId;
	private String	accountNumberLastDigits;
	private String	secondaryAccountId;
	private String	secondaryAccountINumber;
	private String	secondaryAccountNumberLastDigits;
	private Currency	currency;
	private BigDecimal	exchangeRate;
	private BigDecimal	requestedAmount;
	private BigDecimal	approvedAmount;
	private String	authorizationCode;
	private String	transactionResponse;
	private BigDecimal	resultingBalance;
	private BigDecimal	secondaryResultingBalance;
	private Date	transactionTimeStamp;
	private String	description;
	private Boolean	isVoid;
	private Boolean	isReversal;
	private String	receiptNumber;
	private String	avsResponseCode;
	private String	cvv2ResponseCode;
	private String	retrievalReferenceNumber;
	private String	firstName;
	private String	lastName;
	private String	emailAddress;
	private String	phoneNumber;
	private String	street;
	private String	unit;
	private String	city;
	private String	countyOrDistrict;
	private String	stateOrProvince;
	private String	country;
	private String	postalCode;
	private Integer	expirationDay;
	private Integer	expirationMonth;
	private Integer	expirationYear;
	private String	deviceFingerPrintId;
	private String	ipAddress;
	private String	storeNumber;
	private String	terminalNumber;
	private AccountTransactionOfferDetails offerDetails;
	private String	receiptLines;
	private String	termsAndConditions;
	private AccountTransactionType transactionType;
	private PaymentProcessor paymentProcessor;
	private AccountTransactionStatus transactionStatus;
	private AccountType	accountType;
	private PaymentNetworkType	paymentNetworkType;
	private BigDecimal	taxAmount;
	private BigDecimal	transactionFee;
	private MessageReasonCode	messageReasonCode;
	private String	accountNumber;
	private String	activationAccountNumber;
	private String	securityCode;
	private String	additionalRedemptionData;
	private String	productId;
}
